ignore_files:
  - src/components/
  - src/services/
  - src/types/
  - src/App.css
  - src/App.js
  - src/data.js
  - src/index.css
  - src/serviceWorker.js
  - src/setupTests.js
  - .eslintrc.json
  - .eslintignore
  - .stylelintrc.json
  - .stylelintignore
  - .gitignore
  - README.md
  